return {
    {
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        build = ":TSUpdate",
        opts = {
            highlight = { enable = true },
            auto_install = true,
            indent = { enable = true },
            ensure_installed = {
                "bash",
                "c",
                "css",
                "html",
                "java",
                "javascript",
                "json",
                "latex",
                "lua",
                "luadoc",
                "luap",
                "markdown",
                "markdown_inline",
                "proto",
                "python",
                "query",
                "regex",
                "rust",
                "scss",
                "svelte",
                "swift",
                "tsx",
                "typescript",
                "vim",
                "vimdoc",
                "yaml",
            },
        }
    },
}
