# ════════════════════════════════════════════════════════════════════════════
# Configuration files
# ════════════════════════════════════════════════════════════════════════════
source-file ~/.config/tmux/config/plugins.conf
source-file ~/.config/tmux/config/keymaps.conf
source-file ~/.config/tmux/config/options.conf
source-file ~/.config/tmux/themes/catppuccin-latte.conf

run '~/.config/tmux/plugins/tpm/tpm'
