# ════════════════════════════════════════════════════════════════════════════
# Default Theme (Tmux defaults)
# ════════════════════════════════════════════════════════════════════════════
%hidden bg_main="default"
%hidden bg_mid="#2d2d2d"
%hidden bg_separator="#444444"
%hidden fg_main="default"
%hidden fg_inactive="#6e6e6e"
%hidden color_success="#00ff00"
%hidden color_focus="#00ffff"
%hidden color_alert="#ff0000"
%hidden color_activity="#ffff00"