# ════════════════════════════════════════════════════════════════════════════
# Dracula
# ════════════════════════════════════════════════════════════════════════════
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-border-contrast true
set -g @dracula-show-left-icon "#S"
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "
set -g status-justify "centre"
