# ════════════════════════════════════════════════════════════════════════════
# Dracula
# ════════════════════════════════════════════════════════════════════════════
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "cpu-usage ram-usage"
set -g @dracula-border-contrast true
set -g @dracula-show-left-icon "#S"
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "

%hidden bg_main="#282a36"
%hidden bg_mid="#44475a"
%hidden bg_separator="#6272a4"
%hidden fg_main="#f8f8f2"
%hidden fg_inactive="#6272a4"
%hidden color_success="#50fa7b"
%hidden color_focus="#8be9fd"
%hidden color_alert="#ff5555"
%hidden color_activity="#f1fa8c"