# ════════════════════════════════════════════════════════════════════════════
# Gruvbox
# ════════════════════════════════════════════════════════════════════════════
%hidden bg_main="#282828"
%hidden bg_mid="#3c3836"
%hidden bg_separator="#504945"
%hidden fg_main="#ebdbb2"
%hidden fg_inactive="#928374"
%hidden color_success="#b8bb26"
%hidden color_focus="#a89984"
%hidden color_alert="#fb4934"
%hidden color_activity="#fabd2f"