# ════════════════════════════════════════════════════════════════════════════
# Jellybeans
# ════════════════════════════════════════════════════════════════════════════
%hidden bg_main="#060606"
%hidden bg_mid="#333333"
%hidden bg_separator="#404040"
%hidden fg_main="#bcbcbc"
%hidden fg_inactive="#767676"
%hidden color_success="#99ad6a"
%hidden color_focus="#8fbfdc"
%hidden color_alert="#cf6a4c"
%hidden color_activity="#d8ad4c"
