%hidden bg="#282828"
%hidden bg_mid="#3c3836"
%hidden bg_subtle="#504945"
%hidden fg="#ebdbb2"
%hidden fg_muted="#928374"
%hidden green="#b8bb26"
%hidden gray="#a89984"
%hidden red="#fb4934"
%hidden yellow="#fabd2f"

set -g status-bg "$bg"
set -g status-justify "centre"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
set -g status-style "none"

set -g pane-border-style "fg=$bg_subtle"
set -g pane-active-border-style "fg=$gray"

set -g message-style "fg=$bg,bg=$green"
set -g message-command-style "fg=$bg,bg=$green"

setw -g window-status-style "bg=$bg,fg=$fg_muted"
setw -g window-status-activity-style "bg=$bg,fg=$yellow"
setw -g window-status-separator "#[fg=$bg_subtle] "

set -g status-left "#{?client_prefix,#[fg=$bg]#[bg=$red],#[fg=$bg]#[bg=$green]} #S #{?client_prefix,#[fg=$red]#[bg=$bg],#[fg=$green]#[bg=$bg]}#[nobold,nounderscore,noitalics]"
set -g status-right "#{?client_prefix,#[fg=$bg]#[bg=$red],#[fg=$bg]#[bg=$green]} #(whoami) #{?client_prefix,#[fg=$red]#[bg=$bg],#[fg=$green]#[bg=$bg]}#[nobold,nounderscore,noitalics]"

setw -g window-status-format "#[fg=$fg_muted,bg=$bg] #W "
setw -g window-status-current-format "#[fg=$gray,bg=$bg,nobold,nounderscore,noitalics]#[fg=$bg,bg=$gray,bold] #W #[fg=$gray,bg=$bg,nobold,nounderscore,noitalics]"
