# ════════════════════════════════════════════════════════════════════════════
# Unbind
# ════════════════════════════════════════════════════════════════════════════
unbind C-b # prefix
unbind c # create window
unbind d # detach session
unbind D # detach client
unbind f # find window
unbind l # last window
unbind n # next window
unbind o # cycle panes
unbind q # show pane numbers
unbind p # prev window
unbind s # list sessions
unbind w # list windows
unbind z # zoom pane
unbind & # kill window
unbind ! # break pane into window
unbind % # split vertical
unbind "{" # move pane left
unbind "}" # move pane right
unbind '"' # split horizontal
unbind Space # cycle layouts
unbind -T copy-mode-vi MouseDragEnd1Pane

# ════════════════════════════════════════════════════════════════════════════
# General
# ════════════════════════════════════════════════════════════════════════════
# Prefix
set -g prefix C-a

# Reload config alias
set -s command-alias[100] reload="source-file ~/.config/tmux/tmux.conf \; display 'Config Reloaded!'"

# Clear terminal
bind l send-keys C-l

# Vim-like copy/paste
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ════════════════════════════════════════════════════════════════════════════
# Sessions
# ════════════════════════════════════════════════════════════════════════════
bind c detach-client
bind Space choose-tree -s

# ════════════════════════════════════════════════════════════════════════════
# Windows
# ════════════════════════════════════════════════════════════════════════════
# New
bind n command-prompt -p "window name:" "new-window -c '#{pane_current_path}'; rename-window '%%'"

# Navigation
bind -n M-h previous-window
bind -n M-l next-window

# ════════════════════════════════════════════════════════════════════════════
# Panes
# ════════════════════════════════════════════════════════════════════════════
# Split
bind s split-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

# Rotation
bind r rotate-window
bind R rotate-window -D

# Navigation with Neovim
set -g @smart-splits_no_wrap '' # to disable wrapping. (any value disables wrapping)
set -g @smart-splits_move_left_key  'C-h'
set -g @smart-splits_move_down_key  'C-j'
set -g @smart-splits_move_up_key    'C-k'
set -g @smart-splits_move_right_key 'C-l'

# Resize with vim detection
set -g @smart-splits_resize_left_key  'M-Left'
set -g @smart-splits_resize_down_key  'M-Down'
set -g @smart-splits_resize_up_key    'M-Up'
set -g @smart-splits_resize_right_key 'M-Right'
