set -g status-bg "$bg_main"
set -g status-justify "centre"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
set -g status-style "none"

set -g pane-border-style "fg=$bg_separator"
set -g pane-active-border-style "fg=$color_focus"

set -g message-style "fg=$bg_main,bg=$color_success"
set -g message-command-style "fg=$bg_main,bg=$color_success"

setw -g window-status-style "bg=$bg_main,fg=$fg_inactive"
setw -g window-status-activity-style "bg=$bg_main,fg=$color_activity"
setw -g window-status-separator "#[fg=$bg_separator] "

set -g status-left "#{?client_prefix,#[fg=$bg_main]#[bg=$color_alert],#[fg=$bg_main]#[bg=$color_success]} #S #{?client_prefix,#[fg=$color_alert]#[bg=$bg_main],#[fg=$color_success]#[bg=$bg_main]}#[nobold,nounderscore,noitalics]"
set -g status-right "#{?client_prefix,#[fg=$bg_main]#[bg=$color_alert],#[fg=$bg_main]#[bg=$color_success]} #(whoami) #{?client_prefix,#[fg=$color_alert]#[bg=$bg_main],#[fg=$color_success]#[bg=$bg_main]}#[nobold,nounderscore,noitalics]"

setw -g window-status-format "#[fg=$fg_inactive,bg=$bg_main] #W "
setw -g window-status-current-format "#[fg=$color_focus,bg=$bg_main,nobold,nounderscore,noitalics]#[fg=$bg_main,bg=$color_focus,bold] #W #[fg=$color_focus,bg=$bg_main,nobold,nounderscore,noitalics]"
